extends Node

const ICON_PATH = "res://Sprites/Upgrade/"

const UPGRADE = {
	"CLAW": {
		"icon": preload(ICON_PATH+"claw.png"),
		"id":"CLAW",
		"displayname": "CLAW",
		"details": "Claw to attack.",
		"maxLevel" : 1,
		"priceInital" : 2,
		"priceAugmentationByLv" : 1, 
		"prerequisite": [],
	},
	"OXYGENE": {
		"icon": preload(ICON_PATH+"oxygen.png"),
		"id":"OXYGENE",
		"displayname": "GILLS",
		"details": "More time underwater",
		"maxLevel" : 30,
		"priceInital" : 1,
		"priceAugmentationByLv" : 5, 
		"prerequisite": [],
	},
	"SPEED": {
		"icon": preload(ICON_PATH+"vitesse.png"),
		"id":"SPEED",
		"displayname": "SPEED",
		"details": "Gain speed",
		"maxLevel" : 20,
		"priceInital" : 10,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"DASH": {
		"icon": preload(ICON_PATH+"dodge.png"),
		"id":"DASH",
		"displayname": "DASH",
		"details": "Learn to dash",
		"maxLevel" : 1,
		"priceInital" : 14,
		"priceAugmentationByLv" : 1, 
		"prerequisite": ["SWIMMING"],
	},
	"SWIMMING": {
		"icon": preload(ICON_PATH+"swim.png"),
		"id":"SWIMMING",
		"displayname": "SWIMMING",
		"details": "Learn to swim",
		"maxLevel" : 1,
		"priceInital" : 1,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"RESISTANCE": {
		"icon": preload(ICON_PATH+"shield.png"),
		"id":"RESISTANCE",
		"displayname": "RESISTANCE",
		"details": "Take less damages",
		"maxLevel" : 10,
		"priceInital" : 30,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"STRENGHT": {
		"icon": preload(ICON_PATH+"power.png"),
		"id":"STRENGHT",
		"displayname": "STRENGHT",
		"details": "Increase claw's strenght.",
		"maxLevel" : 10,
		"priceInital" : 20,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	}
}
