extends Node

const ICON_PATH = "res://Sprites/Upgrade/"

const UPGRADE = {
	"CLAW": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"CLAW",
		"displayname": "CLAW",
		"details": "Claw to be able to defend yourself.",
		"maxLevel" : 1,
		"priceInital" : 2,
		"priceAugmentationByLv" : 1, 
		"prerequisite": [],
	},
	"OXYGENE": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"OXYGENE",
		"displayname": "MORE OXYGENE",
		"details": "ADD 10 seconds",
		"maxLevel" : 30,
		"priceInital" : 1,
		"priceAugmentationByLv" : 5, 
		"prerequisite": [],
	},
	"SPEED": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"SPEED",
		"displayname": "MORE SPEED",
		"details": "ADD SPEED",
		"maxLevel" : 20,
		"priceInital" : 10,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"DASH": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"DASH",
		"displayname": "DASH",
		"details": "Learn to dash",
		"maxLevel" : 1,
		"priceInital" : 14,
		"priceAugmentationByLv" : 1, 
		"prerequisite": ["SWIMMING"],
	},
	"SWIMMING": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"SWIMMING",
		"displayname": "SWIMMING",
		"details": "Learn to swim",
		"maxLevel" : 1,
		"priceInital" : 1,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"RESISTANCE": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"RESISTANCE",
		"displayname": "RESISTANCE",
		"details": "Lose less oxygen when the enemy attacks you.",
		"maxLevel" : 10,
		"priceInital" : 30,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	},
	"STRENGH": {
		"icon": preload(ICON_PATH+"Joint2.png"),
		"id":"STRENGH",
		"displayname": "STRENGH",
		"details": "Increase attack of claw.",
		"maxLevel" : 10,
		"priceInital" : 20,
		"priceAugmentationByLv" : 30, 
		"prerequisite": [],
	}
}
